name: Simple Check

on:
  pull_request:
    branches: [ main, master ]  # Run on PRs targeting main or master branches
  push:
    branches: [ main, master ]  # Also run when changes are pushed to main/master

jobs:
  verify:
    name: Simple Verification
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run simple check
        run: |
          echo "Running simple verification check"
          # This command will always succeed
          exit 0
